Don't crash when topic param is an invalid string instead of id
Fixes the sentry errors that have appeared like:

  ValueError: invalid literal for int() with base 10: 'Fiscal Policy'

These routes should really be refactored to use Django's url routing
(#792). I'll make a different PR for that.